# Preliminares de Python para Deep Learning: Tensores

Para poder correr y entender modelos de aprendizaje profundo minímo vamos a necesitar lo siguiente: 
1. Técnicas para almacenar y manipular datos
2. Librerias para ingerir y procesar grandes cantidades de datos de diversas fuentes 
3. Operaciones de algebra lineal para datos de altas dimensiones
4. Cálculo para saber en que dirección debemos de ajustar un parámetro para que nuestra función de pérdida disminuya
5. Cálcular parciales automaticamente en python 
6. Fluidez con conceptos de probabilidad y estadística
7. Habilidad para buscar y encontrar respuestas en la documentación de las librerias de python

Acá vamos a ver como usar tensores y sus propiedades, pero esto no incluye todo lo de arriba. En teoria la mayoría de estas cosas ya las saben hacer.

### 1. Manipulación de datos con tensores

La mayoría de las estructuras modernas de deep learning van a usar una clase de tensores (se parece a NumPy pero con más cosas muy útiles para DL). Por ejemplo: MXNet, PyTorch y TensorFlow
   - diferenciación automática
   - aprovecha las GPUs para acelerar el cálculo numérico, mientras que librerias como NumPy usan solo el CPU. 

Estas dos propiedades hacen que los tensores sean perfectos para entrenar, codificar y ejecutar redes neuronales. 

CPU(Unidad Central de Procesamiento): rocesador de propósito general, diseñado para manejar una amplia gama de tareas complejas y administrar el sistema operativo y las aplicaciones. 
GPU(Unidad de Procesamiento Gráfico): procesador especializado, optimizado para realizar cálculos paralelos masivos, especialmente aquellos relacionados con gráficos, visualizaciones y aprendizaje automático


¿Qué es un tensor?
representa un arreglo numérico (probablemente multidimensional). En una sola dimensión un tensor es un vector. Con dos ejes un tensor es una matrix y para $k>2$ solo le llamamos un tensor de orden k. 
El tensor va a ser la interfaz principal para almacenar y manipular datos en librerias de aprendizaje profundo.


In [1]:
import torch 
# arange crea un vector espaciado uniformemente en el rango [0,n)
x = torch.arange(12, dtype=torch.float32)
# cada valor es un elemento del tensor, en este caso tenemos 12 elementos 
print(x)
print(x.numel())
print(x.shape)
# podemos cambiar la forma del tensor usando reshape
X = x.reshape(3,4)
print(X)
# podemos crear tensores de 0's
print(torch.zeros((2,3,4)))
# podemos crear tensores aleatorios con una Gaussiana (0,1)
print(torch.rand(3,4))
# podemos construir tensores usando listas por ejemplo
print(torch.tensor([[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]]))

tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])
12
torch.Size([12])
tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])
tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])
tensor([[0.2178, 0.7959, 0.0477, 0.1052],
        [0.0607, 0.3592, 0.1670, 0.4919],
        [0.7579, 0.1079, 0.1059, 0.5451]])
tensor([[2, 1, 4, 3],
        [1, 2, 3, 4],
        [4, 3, 2, 1]])


##### indexing y slicing de tensores 
Como con una lista de python podemos usar una propiedad muy similar de los tensores

In [3]:
print(X[-1], X[1:3])
# puedes reescribir en el tensor como en una lista en python, dando coordenadas
X[1,2] = 17
print(X)


tensor([ 8.,  9., 10., 11.]) tensor([[ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])
tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5., 17.,  7.],
        [ 8.,  9., 10., 11.]])


##### Operaciones de tensores 

In [6]:
## 1. operaciones escalares
print(torch.exp(x))
## 2. operaciones entre tensores del mismo tamaño 
x = torch.tensor([1.0, 2, 4, 8])
y = torch.tensor([2, 2, 2, 2])
print(x + y)
print(x - y)
print(x * y) 
print(x / y)
print(x ** y)
## 3. concatenacion de tensores: 
X = torch.arange(12, dtype=torch.float32).reshape((3,4))
Y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
print(torch.cat((X, Y), dim=0))
print(torch.cat((X, Y), dim=1))
## 4. tensores logicos 
print(X == Y)
### 5. cantidad de elementos en un tensor 
print(X.sum())

tensor([2.7183e+00, 7.3891e+00, 5.4598e+01, 2.9810e+03])
tensor([ 3.,  4.,  6., 10.])
tensor([-1.,  0.,  2.,  6.])
tensor([ 2.,  4.,  8., 16.])
tensor([0.5000, 1.0000, 2.0000, 4.0000])
tensor([ 1.,  4., 16., 64.])
tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [ 2.,  1.,  4.,  3.],
        [ 1.,  2.,  3.,  4.],
        [ 4.,  3.,  2.,  1.]])
tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
        [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
        [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]])
tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])
tensor(66.)


##### Broadcasting 
Operaciones de tensores que no son exactamente del mismo tamaño: 
- expande los dos arreglos copiando los elementos sobre el eje de dimensión 1, de manera que después de la transformación los dos tensores son del mismo tamaño
- hace operaciones elemento por elemento en estos nuevos tensores

In [ ]:
a = torch.arange(3).reshape((3, 1))
b = torch.arange(2).reshape((1, 2))
print(a,b)
# braodcasting va a producir un arreglo de 3x2  replicando la matriz a sobre las columnas
# y la matriz ve sobre las filas y sumandolas elemento por elemento 
# a expanded [[0,0], [1,1], [2,2]] y b expanded [[0,1],[0,1],[0,1]]
print(a + b)

tensor([[0],
        [1],
        [2]]) tensor([[0, 1]])
tensor([[0, 1],
        [1, 2],
        [2, 3]])


##### Ahorrando memoria
Recordemos que en python la ejecución de operaciones puede provocar la asignación de memoria a los resultados. Si hacemos $Y = X + Y$ python desreferencia el tensor al que apuntaba Y y en su ligar lo apuntamos Y a la memoria recién asignada. Osea después de correr la suma ahora python apunta a Y en una nueva locación.
¿Por qué? porque python primero evalua $Y + X$ guardandolo en un lugar nuevo y después apunta al nuevo lugar en la memoria. 
¿Por qué no queremos que pase esto?
1. No queremos asignar memoria innecesariamente todo el tiempo, por ejemplo para los parámetros de los modelos de ML que se van a estar actualizando, no queremos nueva memoria cada que itera el SGD. 
2. Podríamos apuntar a los mismos parámetros desde múltiples variales. 
La buena noticia es que podemos solucionar esto haciendo operaciones in situ. 

In [10]:
# Problema: 
before = id(Y)
Y = Y + X
id(Y) == before
# Solucion:  
Z = torch.zeros_like(Y)
print('id(Z):', id(Z))
Z[:] = X + Y
print('id(Z):', id(Z))
# también podemos usar  X += Y si no vamos a usar X después
before = id(X)
X += Y
id(X) == before

id(Z): 5172721408
id(Z): 5172721408


True

##### Convirtiendo de numpy a tensores


In [12]:
A = X.numpy()
B = torch.from_numpy(A)
print(type(A), type(B))
a = torch.tensor([3.5])
print(a, a.item(), float(a), int(a))

<class 'numpy.ndarray'> <class 'torch.Tensor'>
tensor([3.5000]) 3.5 3.5 3


### 2. Propiedades de los tensores 
Podemos hacer DL con escalares, vectores y matrices. Pero en general vamos a trabajar con objetos de más dimensiones y acá es cuando nos importa poder usar tensores. En especial se van a volver muy relevantes cuando trabajemos con imagenes. Más de esto después. 

In [15]:
A = torch.arange(6, dtype=torch.float32).reshape(2, 3)
B = A.clone() 
print(A, A + B)
print(A*B) #elementwise product
# multiplicación y suma de escalares
a = 2
X = torch.arange(24).reshape(2, 3, 4)
print(a + X, (a * X).shape)

tensor([[0., 1., 2.],
        [3., 4., 5.]]) tensor([[ 0.,  2.,  4.],
        [ 6.,  8., 10.]])
tensor([[ 0.,  1.,  4.],
        [ 9., 16., 25.]])
tensor([[[ 2,  3,  4,  5],
         [ 6,  7,  8,  9],
         [10, 11, 12, 13]],

        [[14, 15, 16, 17],
         [18, 19, 20, 21],
         [22, 23, 24, 25]]]) torch.Size([2, 3, 4])


In [17]:
## Reducción: 
x = torch.arange(3, dtype=torch.float32)
print(x, x.sum())
print(A.shape, A.sum(axis=0).shape)
print(A.shape, A.sum(axis=1).shape)
print(A.mean(), A.sum() / A.numel())

tensor([0., 1., 2.]) tensor(3.)
torch.Size([2, 3]) torch.Size([3])
torch.Size([2, 3]) torch.Size([2])
tensor(2.5000) tensor(2.5000)


In [18]:
## Suma que no reduce: cuando queremos usar broadcasting
sum_A = A.sum(axis=1, keepdims=True)
print(sum_A, sum_A.shape)
print(A.cumsum(axis=0))

tensor([[ 3.],
        [12.]]) torch.Size([2, 1])
tensor([[0., 1., 2.],
        [3., 5., 7.]])


In [26]:
## Productos punto: 
y = torch.ones(3, dtype = torch.float32)
print(x, y, torch.dot(x, y))

## multiplicacion: matrix-vector 
print(A.shape, x.shape)
print(torch.mv(A, x))
print(A@x)


## multiplicacion: matriz por matriz
B = torch.ones(3, 4)
print(torch.mm(A, B), A@B)

## normas 
u = torch.tensor([3.0, -4.0])
print(torch.norm(u))

tensor([0., 1., 2.]) tensor([1., 1., 1.]) tensor(3.)
torch.Size([2, 3]) torch.Size([3])
tensor([ 5., 14.])
tensor([ 5., 14.])
tensor([[ 3.,  3.,  3.,  3.],
        [12., 12., 12., 12.]]) tensor([[ 3.,  3.,  3.,  3.],
        [12., 12., 12., 12.]])
tensor(5.)


### 3. Diferenciación automática 

Todas las librerias para DL tienen diferenciación automática (autograd).  A medida que pasamos datos a través de cada función sucesiva, la libreria construye un grafo que rastrea cómo cada valor depende de los otros. Para calcular las derivadas, la diferenciación automática funciona a la inversa a través de este grafo aplicando la regla de la cadena. (Recordemos forward y backward passing de las redes neuronales superficiales). 

In [36]:
### Vamos a difrenciar la funcion y = 2x'x
x = torch.arange(4.0)
print(x)

# le asignamos un lugar para guardar nuestra diferenciación
print(x.requires_grad_(True))
# por default el gradiente es None 
print(x.grad)

# nuestra funcion es: 
y = 2 * torch.dot(x, x)
print(y)
# este methodo va a calcular la parcial de y con respecto a x
y.backward()
print(x.grad)

## sabemos que el graidente tiene que ser 4x
print(x.grad == 4*x)


## detaching: ejemplo si tenemos z = x * y , y = x * x pero queremos calcular la influencia directa de x en z, podemos 
## crear una nueva variable que borre como fue creada y. Asi que no va a haber ancentro en el grafo, por ejemplo
## sacar el gradiente de z con respecto a x, seria y, y no 3x**2

print(x.grad.zero_())
y = x * x
u = y.detach()
z = u * x
z.sum().backward()
x.grad == u

## pero todavia podemos calcular el gradiente de y con respecto de x: 
x.grad.zero_()
y.sum().backward()
x.grad == 2 * x


tensor([0., 1., 2., 3.])
tensor([0., 1., 2., 3.], requires_grad=True)
None
tensor(28., grad_fn=<MulBackward0>)
tensor([ 0.,  4.,  8., 12.])
tensor([True, True, True, True])
tensor([0., 0., 0., 0.])


tensor([True, True, True, True])

### 4. Documentacion

In [37]:
## Para saber que funciones y clases pueden ser llamadas usamos 'dir' 
print(dir(torch.distributions))
## Si queremos mas info de una función o clase en particular 
print(help(torch.ones))

['AbsTransform', 'AffineTransform', 'Bernoulli', 'Beta', 'Binomial', 'CatTransform', 'Categorical', 'Cauchy', 'Chi2', 'ComposeTransform', 'ContinuousBernoulli', 'CorrCholeskyTransform', 'CumulativeDistributionTransform', 'Dirichlet', 'Distribution', 'ExpTransform', 'Exponential', 'ExponentialFamily', 'FisherSnedecor', 'Gamma', 'Geometric', 'Gumbel', 'HalfCauchy', 'HalfNormal', 'Independent', 'IndependentTransform', 'InverseGamma', 'Kumaraswamy', 'LKJCholesky', 'Laplace', 'LogNormal', 'LogisticNormal', 'LowRankMultivariateNormal', 'LowerCholeskyTransform', 'MixtureSameFamily', 'Multinomial', 'MultivariateNormal', 'NegativeBinomial', 'Normal', 'OneHotCategorical', 'OneHotCategoricalStraightThrough', 'Pareto', 'Poisson', 'PositiveDefiniteTransform', 'PowerTransform', 'RelaxedBernoulli', 'RelaxedOneHotCategorical', 'ReshapeTransform', 'SigmoidTransform', 'SoftmaxTransform', 'SoftplusTransform', 'StackTransform', 'StickBreakingTransform', 'StudentT', 'TanhTransform', 'Transform', 'Transform